DROP TABLE IF EXISTS keyword_mapping;

CREATE TABLE keyword_mapping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    keyword TEXT NOT NULL,
    intent TEXT,
    loan_type TEXT,
    message_type TEXT,
    subprocess TEXT
);

-- === INTENT MAPPINGS ===
INSERT INTO keyword_mapping (keyword, intent) VALUES
('new', 'New Loan Inquiry'),
('apply', 'New Loan Inquiry'),
('application', 'New Loan Inquiry'),
('enquire', 'New Loan Inquiry'),
('interested', 'New Loan Inquiry'),
('new application', 'New Loan Inquiry'),
('loan enquiry', 'New Loan Inquiry'),
('savings', 'Savings Account Inquiry'),
('savings account', 'Savings Account Inquiry'),
('current account', 'Savings Account Inquiry'),
('open account', 'Account Opening'),
('close', 'Loan Closure'),
('close loan', 'Loan Closure'),
('terminate', 'Loan Closure'),
('cancel', 'Loan Closure'),
('repay', 'Repayment Issue'),
('repayment', 'Repayment Issue'),
('payment', 'Repayment Issue'),
('due', 'Repayment Issue'),
('missed', 'Repayment Issue'),
('overdue', 'Repayment Issue'),
('receipt', 'Repayment Issue'),
('interest', 'Interest Rate Query'),
('rate', 'Interest Rate Query'),
('roi', 'Interest Rate Query'),
('percentage', 'Interest Rate Query'),
('document', 'Document Submission'),
('upload', 'Document Submission'),
('send', 'Document Submission'),
('loan status', 'Loan Status Update'),
('track', 'Loan Status Update'),
('status', 'Loan Status Update'),
('update', 'Loan Status Update'),
('prepay', 'Prepayment Request'),
('pre-payment', 'Prepayment Request'),
('pre payment', 'Prepayment Request'),
('partpay', 'Part-Payment Request'),
('part-payment', 'Part-Payment Request'),
('part payment', 'Part-Payment Request'),
('partial', 'Part-Payment Request'),
('transfer', 'Balance Transfer Request'),
('balance transfer', 'Balance Transfer Request'),
('switch', 'Balance Transfer Request'),
('topup', 'Top-Up Loan Request'),
('top-up', 'Top-Up Loan Request'),
('top up', 'Top-Up Loan Request'),
('additional', 'Top-Up Loan Request'),
('statement', 'Loan Statement Request'),
('loan statement', 'Loan Statement Request'),
('summary', 'Loan Statement Request'),
('report', 'Loan Statement Request'),
('eligibility', 'Loan Eligibility Check'),
('loan eligibility', 'Loan Eligibility Check'),
('eligible', 'Loan Eligibility Check'),
('guarantor', 'Co-Applicant or Guarantor Issue'),
('coapplicant', 'Co-Applicant or Guarantor Issue'),
('co-applicant', 'Co-Applicant or Guarantor Issue'),
('rejection', 'Loan Rejection Appeal'),
('loan rejection', 'Loan Rejection Appeal'),
('declined', 'Loan Rejection Appeal'),
('appeal', 'Loan Rejection Appeal'),
('query', 'General Query'),
('doubt', 'General Query'),
('clarify', 'General Query'),
('information', 'General Query'),
('account help', 'General Account Query'),
('bank query', 'General Account Query');

-- === LOAN TYPE MAPPINGS ===
INSERT INTO keyword_mapping (keyword, loan_type) VALUES
('home', 'Home Loan'),
('house', 'Home Loan'),
('property', 'Home Loan'),
('flat', 'Home Loan'),
('apartment', 'Home Loan'),
('personal', 'Personal Loan'),
('individual', 'Personal Loan'),
('education', 'Education Loan'),
('school', 'Education Loan'),
('college', 'Education Loan'),
('tuition', 'Education Loan'),
('auto', 'Auto Loan'),
('car', 'Auto Loan'),
('vehicle', 'Auto Loan'),
('bike', 'Auto Loan'),
('credit', 'Credit Card Loan'),
('card', 'Credit Card Loan'),
('creditcard', 'Credit Card Loan'),
('gold', 'Gold Loan'),
('jewellery', 'Gold Loan'),
('ornament', 'Gold Loan'),
('business', 'Business Loan'),
('enterprise', 'Business Loan'),
('startup', 'Business Loan'),
('msme', 'MSME Loan'),
('small', 'MSME Loan'),
('medium', 'MSME Loan'),
('micro', 'MSME Loan'),
('agriculture', 'Agriculture Loan'),
('farm', 'Agriculture Loan'),
('crop', 'Agriculture Loan'),
('emergency', 'Emergency Loan'),
('urgent', 'Emergency Loan'),
('medical', 'Emergency Loan'),
('general', 'General Loan');

-- === MESSAGE TYPE MAPPINGS ===
INSERT INTO keyword_mapping (keyword, message_type) VALUES
('query', 'Query'),
('question', 'Query'),
('ask', 'Query'),
('want', 'Request'),
('please', 'Request'),
('kindly', 'Request'),
('request', 'Request'),
('problem', 'Complaint'),
('issue', 'Complaint'),
('complaint', 'Complaint'),
('error', 'Technical Issue'),
('bug', 'Technical Issue'),
('not working', 'Technical Issue'),
('feedback', 'Feedback'),
('suggestion', 'Feedback'),
('recommendation', 'Feedback'),
('thank you', 'General Communication'),
('regards', 'General Communication'),
('grievance', 'Complaint'),
('dispute', 'Complaint'),
('concern', 'Complaint'),
('escalation', 'Complaint');

-- === SUBPROCESS MAPPINGS ===
INSERT INTO keyword_mapping (keyword, subprocess) VALUES
('open account', 'Account Opening'),
('account creation', 'Account Opening'),
('account opening', 'Account Opening'),
('disburse', 'Disbursement'),
('disbursement', 'Disbursement'),
('payout', 'Disbursement'),
('foreclose', 'Foreclosure'),
('foreclosure', 'Foreclosure'),
('close loan', 'Foreclosure'),
('collection', 'Collection Process'),
('follow up', 'Collection Process'),
('pay', 'Payment Handling'),
('payment', 'Payment Handling'),
('transaction', 'Payment Handling'),
('refund', 'Refund Request'),
('return', 'Refund Request'),
('charge', 'Charges & Fees'),
('fee', 'Charges & Fees'),
('processing fee', 'Charges & Fees'),
('restructure', 'Loan Restructuring'),
('extend', 'Loan Restructuring'),
('reschedule', 'Loan Restructuring'),
('complaint', 'Feedback or Complaint'),
('escalate', 'Feedback or Complaint'),
('legal', 'Legal Related'),
('lawyer', 'Legal Related'),
('settle', 'Settlement'),
('negotiation', 'Settlement'),
('document', 'Document Submission'),
('upload', 'Document Submission'),
('recover', 'Recovery'),
('seize', 'Recovery'),
('check status', 'Loan Status Check'),
('loan status', 'Loan Status Check'),
('track', 'Loan Status Check'),
('eligibility', 'Eligibility Check'),
('qualified', 'Eligibility Check'),
('statement', 'Statement Request'),
('loan statement', 'Statement Request'),
('summary', 'Statement Request'),
('account statement', 'Statement Request'),
('savings', 'General Banking'),
('general', 'General Sub-process'),
('other', 'General Sub-process');
